### ISSUE TITLE
Bug in train_mamba.py line 53

### ISSUE THREAD

**Issue by vmajor** [havenhq/mamba-chat#2]
Default code generates:

```
~/site-packages/transformers/trainer.py", line 1597, in _inner_training_loop
    max_steps = math.ceil(args.num_train_epochs * num_update_steps_per_epoch)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: must be real number, not str
```

Changing the line 53 to `int` corrects this error: `parser.add_argument("--num_epochs", type=int, default=1`

**Comment by rwl4** [comment]
I submitted a pull request that resolves this. You can check my fork in the meantime.

https://github.com/rwl4/mamba-chat

**Comment by rwl4** [comment]
This should be fixed now.

**Comment by justusmattern27** [comment]
@rwl4's commit fixes this: https://github.com/havenhq/mamba-chat/pull/1
