### ISSUE TITLE
ImportError: /usr/local/lib/python3.10/dist-packages/causal_conv1d_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

### ISSUE THREAD

**Issue by venkat-p-r** [havenhq/mamba-chat#21]
ImportError                               Traceback (most recent call last)
[<ipython-input-1-a28a4a4ea4d7>](https://localhost:8080/#) in <cell line: 4>()
      2 import argparse
      3 
----> 4 from mamba_ssm.models.mixer_seq_simple import MambaLMHeadModel
      5 from transformers import AutoTokenizer, TrainingArguments
      6 from trainer.data import ChatDataModule

3 frames
[/usr/local/lib/python3.10/dist-packages/causal_conv1d/causal_conv1d_interface.py](https://localhost:8080/#) in <module>
      5 
      6 
----> 7 import causal_conv1d_cuda
      8 
      9 

ImportError: /usr/local/lib/python3.10/dist-packages/causal_conv1d_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

I am facing above error when starting the fine-tuning in Google Colab.

**Comment by Rohith04MVK** [comment]
Could you try installing `causal-conv1d` manually and not from the requirements using `pip install causal-conv1d` ?
