### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by fakerybakery** [havenhq/mamba-chat#4]
Hi,
Very interesting! Are you planning to release a demo on HF spaces?

**Comment by sanjay920** [comment]
an option is for you to run it in Google Colab

**Comment by justusmattern27** [comment]
Hey, I've prepared a Google Colab notebook with the ability to test the model through the cli. Feel free to check it out [here](https://colab.research.google.com/drive/1dUlEYnRbgJYg4_kofNpsCddLCh6vltNK?usp=sharing)

**Comment by justusmattern27** [comment]
I've just merged @BlenderWang9487 's demo PR, thanks for the contribution! You can now run a local gradio app:

`python app.py --share`

Closing this issue now :)
